### ISSUE TITLE
Concurrency issues with component type registration result in duplicate key exception

### ISSUE THREAD

**Issue by immortius** [genaray/Arch#239]
This is in 1.3.0-alpha. Situation is running unit tests, so likely a concurrency issue where multiple threads are (indirectly) registering component types at the some time. I would suggest ComponentRegistry.Add should lock, double check the component type hasn't already been registered, and then proceed to register - returning the existing entry if it has been registered prior. 

Otherwise the solution is for Arch users to preregister components in any situation where they may be utilizing multiple threads - running server and client threads, running multiple worlds on different threads, etc.

```An exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'An item with the same key has already been added. Key: TestStringComponent'
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Arch.Core.Utils.ComponentRegistry.Add(Type type, Int32 typeSize)
   at Arch.Core.Utils.ComponentRegistry.Add(Type type)
   at Arch.Core.Utils.Component.GetComponentType(Type type)
   at Arch.Core.Utils.ComponentType.op_Implicit(Type value)```

**Comment by Shadowblitz16** [comment]
Can we get lock free concurrency?
I hear locks are slow.

Maybe requiring the use of record structs instead of mutable structs would help.

**Comment by immortius** [comment]
For clarity, this issue is around registering component types into the Component registry, not adding components to an entity. So it is an operation that occurs a very limited number of times (once for each component type over the lifetime of application). It occurs because the component registry is global and added to automatically when a component type is encountered the first time.

The issue is also a duplicate key error when adding to the internal dictionary, not anything to do with structs or the nature of the component types themselves.

If there is a solution that doesn't involve locks then that would be ideal. But I would suggest that the cost of a lock here would be minimal due to the relatively small number of times it would even occur - since a check for existence can be made prior to creating the lock and the vast majority of the time it will be found.
