### ISSUE TITLE
macOS arm64 support

### ISSUE THREAD

**Issue by lihaochen910** [genaray/Arch#76]
SDK: 7.0.202 arm64
Maybe arm64 is not supported?
```log
Arch/src/Arch.Samples/bin/Debug/net7.0/Arch.Samples
Sample App starts...
Unhandled exception. System.TypeInitializationException: The type initializer for 'Arch.Core.Utils.Group`1' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Arch.Core.Utils.Component`1' threw an exception.
 ---> System.ArgumentException: Type 'Arch.Samples.Sprite' cannot be marshaled as an unmanaged structure; no meaningful size or offset can be computed.
   at System.Runtime.InteropServices.Marshal.SizeOfHelper(Type t, Boolean throwIfNotMarshalable)
   at Arch.Core.Utils.Component`1..cctor() in /Users/Kanbaru/GitWorkspace/Arch/src/Arch/Core/Utils/CompileTimeStatics.cs:line 290
   --- End of inner exception stack trace ---
   at Arch.Core.Utils.Group`1..cctor() in /Users/Kanbaru/GitWorkspace/Arch/src/Arch/Arch.SourceGen/Arch.SourceGen.QueryGenerator/CompileTimeStatics.g.cs:line 12
   --- End of inner exception stack trace ---
   at Arch.Samples.ColorSystem..ctor(World world) in /Users/Kanbaru/GitWorkspace/Arch/src/Arch.Samples/Systems.cs:line 162
   at Arch.Samples.Game.BeginRun() in /Users/Kanbaru/GitWorkspace/Arch/src/Arch.Samples/Game.cs:line 67
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Program.<Main>$(String[] args) in /Users/Kanbaru/GitWorkspace/Arch/src/Arch.Samples/Program.cs:line 15

Process finished with exit code 134.
```

**Comment by genaray** [comment]
Thanks! 

I bet you tried ro run the samples from the master? Im gonna investigate that issue ^^

**Comment by lihaochen910** [comment]
yes, thats it.

**Comment by genaray** [comment]
As a workaround manual component registration can be used : https://github.com/genaray/Arch/wiki/Utility-Features#manual-component-registration.
